# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0004_auto_20161108_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='responded',
            field=models.BooleanField(default=False),
        ),
    ]
