# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0005_person_responded'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='responded_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
