# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-27 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0006_person_responded_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='ceremony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invitation',
            name='shuttle',
            field=models.BooleanField(default=False),
        ),
    ]
